name: Build and Deploy to `pages` Branch for Vercel

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: pnpm install

    - name: Patch theme text
      run: |
        sed -i 's/自豪地使用 %s 主题/正在使用 %s 主题.apk/' node_modules/hexo-theme-kratos-rebirth/languages/zh-CN.yml

    - name: Generate site with Hexo
      run: npx hexo generate --force

    - name: Deploy to `pages` branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        mkdir deploy_dir
        cp -r public/* deploy_dir/

        cd deploy_dir
        git init
        git checkout -b pages
        git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}

        git add .
        git commit -m "Deploy Hexo site from commit ${{ github.sha }}"
        git push origin pages --force
